### ISSUE TITLE
Confirm consistent usage of getReferenceToJacobian

### ISSUE THREAD

**Issue by jtencer** [Pressio/pressio#108]
If the Jacobian (decoder not ODE) is not constant, we need to confirm that the correct Jacobian is used in all cases.  This would also enable a time-varying Jacobian.

**Comment by fnrizzi** [comment]
@jtencer can you please list here what are the rules in your view that one should check for making sure the "correct jacobian" is used?

**Comment by jtencer** [comment]
Currently, the user defined mapping interface includes getReferenceToJacobian() which is called whenever the Jacobian is queried.  To support nonlinear mappings and time-varying Jacobians, we need to:

1. Confirm that there is no scenario when the Jacobian could need to be updated in between calls to getReferenceToJacobian
2. Include the ROM state as an argument to getReferenceToJacobian i.e. jacobian_type & getReferenceToJacobain(const rom_state_type & romState)
3. Confirm that getReferenceToJacobian is only called once per rom state update to avoid unnecessary updates.

Because 2 has not been completed, my hacky implementation currently updates the Jacobian as part of applyMapping which results in unnecessary updates.

**Comment by fnrizzi** [comment]
@jtencer @eparish1 @pjb236 

Ok, let's go in order, since this is important: 

- currently, the decoder's Jacobian is taken by reference. so if you change it on your side, at any time, this will affect pressio too. This is dangerous but also helps avoiding copying data back and forth. 

- I need to make sure pressio calls `getReferenceToJacobian` *only once* to store the reference just to make things more clear (this should not change anything as far as the numerics because calling `getReference` many times, simply restores the references which is ugly, so i will fix this. 

-

**Comment by jtencer** [comment]
In the regression test I have 
`void updateJacobian(const rom_state_type & romState) const`

My thought was that we would call that method from `getReferenceToJacobian` rather than having Pressio call it separately.  This was the reason I wanted to avoid spurious calls to `getReferenceToJacobian`.  If Pressio calls `updateJacobian` separately, then additional calls to `getReferenceToJacobian` aren't a big deal because there would be no computation involved in that op.

I think it's appropriate to only update the Jacobian once per full iteration.  I think that if the Jacobian is changing significantly within an iteration, that either the step is too large or the manifold is too crinkly.

**Comment by fnrizzi** [comment]
@jtencer what if I call the `updateJacobian` method **before** starting a new step?

**Comment by jtencer** [comment]
I think we need to write out the equations we’re solving and figure out at what level we’re ok with linearization.  That should be what governs the frequency we update the Jacobians.

**Comment by fnrizzi** [comment]
Yes, makes sense... would you be able, please, to start this? and then we can follow up here. 
This being said, I will not include this in the new upcoming release ok?  :)

**Comment by jtencer** [comment]
I think we need to call `computeJacobian` each time we compute the ROM Jacobian.  I don't think we need to recompute the old steps though.

**Comment by fnrizzi** [comment]
This relates to #107 


> I think we need to call `computeJacobian` each time we compute the ROM Jacobian. I don't think we need to recompute the old steps though.

Ok. So why don't we need to recompute old steps? can you post a pdf here with the math you did to figure this out?

**Comment by jtencer** [comment]
Because the appropriate decoder Jacobian for computing the old steps is the one that's evaluated at the old step.  The time integrator shouldn't need to be aware of anything besides the history of states and the method for computing the next state given the prior states.  What would be the justification for changing prior state information based on the current state?

**Comment by fnrizzi** [comment]
> What would be the justification for changing prior state information based on the current state?

None! I agree with you! just wanted to make sure :)

**Comment by fnrizzi** [comment]
@jtencer @eparish1 @pjb236 
I am working on this and came across the following: implicit Galerkin with the discrete-time API, but I think the same happens with LSPG. 

Let's say we are a at a newton step `k` and let's call the decoder's jacobian `J_d`.

If we update the decoder's Jacobian ONLY when we compute the ROM Jacobian, then we have a discrepancy because at `k` the ROM residual computation will use the previous `J_d` while the computation of the ROM Jacobian will use the new `J_d`. So shouldn't we update the decoder's Jacobian once at the beginning of every solver's step?

**Comment by pjb236** [comment]
I don't see a way around that if we want to be mathematically correct. J_d should be computed whenever we update the state. However, updating J_d for every Newton step could be very costly.

**Comment by fnrizzi** [comment]
what if pressio passes you also the time step we are at? that way you can decide whether to update or not. 
would that make sense?

**Comment by fnrizzi** [comment]
- solver owns when to update Jacobian
