### ISSUE TITLE
Inconsistent use of "product" for matrix and multivectors

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#109]
For eigen, we have ops_mat_prod_mat.hpp which can do a product of matrix types. For Kokkos and Tpetra, we have ops_mvec_prod_mvec.hpp, which can only do of product of multivector types.  I propose we add mat_prod_mat.hpp for matrix types for Kokkos and tpetra, and consistently call the file ops_mat_prod_mat.hpp

**Comment by fnrizzi** [comment]
@eparish1 yes, we need to separate the operations involving matrices from those involving multivectors. 
So basically we need something like: ops_mat_prod_mat, ops_mvec_prod_mvec because we might implement things differently.

**Comment by fnrizzi** [comment]
@eparish1 I fixed this, now the operations involving matrices or multivector are in ops_level3.hpp while those for matrix/multivector-vector are in ops_level2.hpp. This is consistent with blas notation. Btw, this is just a file name, so it does not really matter since all operations are called `product` anyway. But the new naming is better.
