### ISSUE TITLE
preliminary feedback on what is missing from c++ documentation

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#283]
@pjb236 @eparish1 @jtencer @kennychowdhary 

Objective: provide *detailed* feedback on what is missing (from your point of view) from the [C++ docs](https://pressio.github.io/pressio/html/index.html) 

Deliverable: please comment on this issue with your response

**Comment by pjb236** [comment]
Overall, when we add content in the placeholders and fix the broken links, I think we will have decent documentation for the C++ version of Pressio. It seems like most of the missing content is under the “hyperreduction”, “classes”, and “namespaces” tabs. However there are a number of missing pieces elsewhere. 

**Main Page**:

https://pressio.github.io/pressio/html/index.html

Overall, I’m happy with this page. Just a few minor comments and questions:

Why does the “test subdirectory” link go directly to the Burgers 1D example?

The “Classes” and “Namespaces” tabs are empty. Should we use doxygen to populate these?

Side note: should we offer option for discrete-time API w/o Jacobian? We could provide a finite difference capability for this case. Maybe we offer something similar for the continuous-time API as well?

**Adapter API**:

https://pressio.github.io/pressio/html/md_pages_coreconcepts_adapter_api.html

Overall this is good, but incomplete
-Finish up “todo” items? What else do we want to say here?
-“Should one prefer the continuous-time or discrete-time API?” Might be good to put this up top (after “What is it?…”), say more on why we prefer the velocity API

**Installation and Dependencies**:

https://pressio.github.io/pressio/html/md_pages_getstarted_build_and_install.html

Table of cmake variables: when something is “automatically on”, is it optional? The text below seems to imply not, so we might want to choose our wording to make this clear in the table as well.

Consistent emphasis on “Pressio”? Sometimes the name is emphasized in the text, other time it is not

Yellow lined comment box at bottom: what exactly are we turning on/off? Not sure I follow this comment in general…

**Components**:

https://pressio.github.io/pressio/html/md_pages_getstarted_packages.html

Component table: links do not work for me, maybe they are broken since the master branch has been renamed?

**Tutorials**:

https://pressio.github.io/pressio/html/md_pages_tutorials.html

Do we need a paragraph maybe explaining how to go thought the tutorials? For example, stating that each tutorial covers a key functionality in pressio and to contact us if you want more?

**Linear decoder tutorial**:

https://pressio.github.io/pressio-tutorials/html/md_pages_rom_tutorial1.html

Missing link to data structures page

Should we just split this into 2 seperate pages for the natively supported and custom ops?

“Comments”: should we display this offer to increase support more prominently elsewhere on the website?

**Default Galerkin Explicit Time**:

https://pressio.github.io/pressio-tutorials/html/md_pages_rom_tutorial2.html

Missing source code

“Pressio4py” mentioned here. Guess we copied this over but haven’t edited it entirely yet.

Broken or missing links throughout

**Shallow Water Equation Tutorial**:

https://pressio.github.io/pressio-tutorials/html/md_pages_swe_lspg.html

Typo in the equation for the full state approximation, \hat{x} on left-hand side should be \tilde{x}

Missing link (todo flag) to observer class documentation

Broken link at bottom of page

https://pressio.github.io/pressio-tutorials/html/md_pages_swe_hrlspg.html

Should link to an explanation of sample vs. stencil mesh. 

**Data Types and Structures**:

https://pressio.github.io/pressio/html/md_pages_coreconcepts_datatypes.html

Incomplete

**Hyperreduction**:

https://pressio.github.io/pressio/html/md_pages_hyperreduction.html

Incomplete. Should probably limit this to describe how to set a masked or hyper-reduced ROM object in Pressio, link to Pressio-tools documentation for info on pre-processing.

**Comment by eparish1** [comment]
**High-level things that I think should be added that aren’t currently there**
•	A page for the observer. In general, I think this is a very important thing to usability.
•	Code synopses like done in the Python documentation that gives the user a quick-reference guide for setting things up
o	APIs
o	Decoders
o	Time marching schemes
o	ROM schemes
o	Linear solvers
o	Nonlinear solvers
o	Observer 
•	Code templates that provide the user with code that they could copy and paste, and then fill in what they need. I recommend here we provide recommended solvers, time marching schemes, etc. For each one, it would be ideal to show Eigen and Kokkos, and with the various hyper-reduction techniques we have
o	Galerkin 
o	LSPG 
o	WLS 
o	Maybe a FOM driver that just does time stepping

**Specifics.**
Adapter API. 
•	Continuous-time API has a “todo finish”
•	Change “we envision” to “Pressio is designed for”
•	“Where can you use the AdapterB”. WLS makes sense for both explicit and implicit integration.
•	Discrete-time API has a “todo finish”
•	Double check the residual API inputs, is it dt^n?
•	Not clear in the discrete time API how different stencils are handled 

Installation and Dependencies
•	Typo in “linking to it”
•	Typo in: “The main reason for doing this is that we aim to alleviate the user from writing custom operations and allows pressio to decide when and how to leverage the native libraries' operations to obtain the best performance.”
•	Installation and dependencies: I think it would be nice to have an end-to-end example
•	
Linear decoder tutorial
•	Missing links on supported data structures
•	Repeated content in Linear decoder custom and natively supported types tutorial

Default Galerkin with explicit time stepping
•	Missing links (FOM object satisfying the API)
•	Broken linear decoder link
•	Broken link for step [5]
•	Todo at the end of how to create a default Galerkin problem
•	Todo at end of tutorial

SWE tutorial
•	Objective should be at top
•	Broken link in FOM driver
•	Inconsistency between physical domain in problem definition and FOM driver 
•	Add link in FOM driver back to main tutorial, or to next step
•	In LSPG, ensure consistency of the x vs y notation
•	Broken link to observers
•	Broken link at end of standard LSPG tutorial
•	Update hyper-reduction tutorial with changes Francesco made (e.g., no longer link to swe2d_hyper)
•	Broken link for swe2d_hyper & swe2d
•	Broken link at the end

Data Types and Structures, Hyper-reduction, classes, and namespaces
•	Needs development
I’d start at data-types, then go to hyper-reduction
