### ISSUE TITLE
rom: finalize problem factory functions (`create`): API and doxygen

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#292]
- create function API: https://github.com/Pressio/pressio/blob/main/include/rom/galerkin/rom_create_default_galerkin_problem.hpp

- continuous time API test: https://github.com/Pressio/pressio/blob/main/tests/rom/burgers1d/galerkin/eigen/default_galerkin_bdf1_continuous_time_api/main.cc

- discrete-time API test: https://github.com/Pressio/pressio/blob/main/tests/rom/burgers1d/galerkin/eigen/default_galerkin_bdf1_discrete_time_api/main.cc

**Comment by MikolajZuzek** [comment]
The code seems pretty immediately readable, given that one understands the underlying math concepts.

`createDefaultProblem()` function is a nice, static, templated factory that instantiates _default problem_ class selected by API type and time stepper:
![createDefaultProblem](https://user-images.githubusercontent.com/29018159/123087590-05232580-d425-11eb-8cdd-bf8888ddb739.png)
(Source: [createDefaultProblem.uml.txt](https://github.com/Pressio/pressio/files/6701357/createDefaultProblem.uml.txt))

**Comment by MikolajZuzek** [comment]
There might be slight design inconsistency at the top level: `createDefaultProblem()` is named and specialized as a single, generic (i.e. API type agnostic) function, but it takes different _explicit_ template parameters for the two cases: `stepper_tag` for continuous API and `rom_jacobian_type` for discrete API.

I'm not sure if it's a real concern, but if it was, the possible solutions would be to:
 1. de-generalize the function by creating two clearly different versions for continuous and discrete API;
 2. get rid of differentiating template parameters, for instance by defining them on the adapter (as ROM configuration options).

With the later solution, we'd get:
[![generalized](https://user-images.githubusercontent.com/29018159/123090173-22a5be80-d428-11eb-9cf9-8e4606ec541b.png)](http://www.plantuml.com/plantuml/uml/hP9FYzim4CNl-XH3ScWBkvjUUX56RDZi8OUoIzjZ8SZoEAXh_M4aGqF9Tw-asatZ1Dm_dPCPpNk_vv7kGvGKUzEnyAAjboGDaEjjy-388i4xnhnKBtAFiF248MZ7EJd3-LvsI4cpW2MMWcyCW515QVTT6gzgeGXbn0ssik_YCxcwGrEjQl5QUdy33IhN8Dt0eGfzBJuylQzM-UDd0ziVZJSBa06kcR647FDfupjODgLAbjEHSZP6RN1oV17N6Uy2veJLm145FHpiiWyisrB5uNY6QNHG_mEJVIOODh6PxBGMZrzzfvMEsVLZH9zQ3ocjjhthGsv-Ii7MNXVGkNgKPjb9CyoFEMO3RCrV1oZIVmwmILiZZFWBAtzUuOsJbuGZIwk-zj3WzbQSFmCEgaHDIM7zl9rNbLlbq0pm8c9dbdTtui-kvcsgjWKEECn1fONqdlEG11vf5-M-McannzcQt-DeCyyv_MpYp6t-mdcrfbf7adI0fytZPpk2o9dT5wbShQNTnOF7Wdl5xj4slUc-0m00)

**Comment by fnrizzi** [comment]
@MikolajZuzek thanks for the feedback! 
- what you think it is a problem to have the function with same name but differentiating via explicit template parameters?

**Comment by MikolajZuzek** [comment]
Thanks @fnrizzi, let's stick to the first perspective then: two overloads for two distinct variants.
I don't see any problem with keeping the same name for them since they do the same thing.

For a generic `createDefaultProblem<P>(A, ...)` call, we specialize on `(P, A)` determining continuous vs discrete variant.  
Current implementation inspects adapter `A`, which seemed superfluous - we could just check "explicit" parameter `P` at hand (type of stepper or Jacobian): for instance, when someone calls `createDefaultProblem<>(A0, ...)`, we know `A0` is discrete API with default Jacobian - without looking into it with the predicate. Then I realized that, in general case, we actually know as little of `P` as of `A`, so those implementations are kind of equally good (and thus there is no inconsistency in the design).

> Note: That explicitness of `P` should be achievable with stepper typing tricks - then we could get rid of all `enable_if` predicates - but it doesn't seem to be straightforward nor worth the effort (better just differentiate function overloads by name).

I posted the alternative implementation, specializing on parameter (stepper vs Jacobian) instead of adapter on temporary [branch `tmp-292`](https://github.com/Pressio/pressio/blob/tmp-292/include/rom/galerkin/rom_create_default_galerkin_problem.hpp). It's not a fix (as explained above) and I'm not sure if it's any improvement, but maybe you'll find something useful in the changes.

**Comment by fnrizzi** [comment]
@MikolajZuzek thanks, I like this better!
Could you now check for the same kind of thing in the following functions: 
- masked galerkin problem:  https://github.com/Pressio/pressio/blob/main/include/rom/galerkin/rom_create_masked_galerkin_problem.hpp
- hyper-reduced galerkin problem: https://github.com/Pressio/pressio/blob/main/include/rom/galerkin/rom_create_hyperreduced_galerkin_problem.hpp

**Comment by MikolajZuzek** [comment]
Hi @fnrizzi !

I created branch [`292-review-create-functions`](https://github.com/Pressio/pressio/tree/292-review-create-functions):
* As we discussed, valid concern discussed in [the article](https://cor3ntin.github.io/posts/variadic/) is not an issue here in our case, because no parameters are placed after `Args && ... args` so they remain terminal and can be resolved unambiguously to `typename ...Args` by the compiler, regardless of trailing `return_t` placed in `template<...>` declaration after that;
* I've fixed and expanded the changes we discussed above to all Galerkin and LSPG functions;
* LSPG steady functions have only one specialization each, so I moved the predicates from `enable_if` to `static_assert` - in a similar way to how we changed that in continuous and discrete API deduction (that's a separate commit for clarity).

**Comment by fnrizzi** [comment]
done

**Comment by MikolajZuzek** [comment]
Deleted `292-review-create-functions` branch: those of the proposed and discussed changes, that were accepted, were applied during recent overall refactoring.
