### ISSUE TITLE
tests: fix gtest expect/assert if used incorrecrtly

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#437]
@mzuzek you raise a good point: 
- we should explore all `ops`, `ode`, `rom`, tests to make sure that we use the correct gtest macro for accumulation vs exact equality 
- one PR for each component

**Comment by mzuzek** [comment]
@fnrizzi

Here's the review of `EXPECT_DOUBLE_EQ` suspected usage in tests on [`develop` at 7d2dbb9](https://github.com/Pressio/pressio/tree/7d2dbb9c324775e123173f5869da75c046bcb83d). Let me know what you think of categories and what's your opinion on which cases should be fixed (i.e. exact `EXPECT_DOUBLE_EQ` replaced with tolerance-based `EXPECT_NEAR`, like in #438).

### literal

Comparisons against literal expressions - like `EXPECT_DOUBLE_EQ(R(7), 21*1.+22*2.+23*3.+1.)` - were excluded as _not_ suspected (i.e. correctly assuming highest level of accuracy). This includes also indirect cases where a literal is first assigned to a variable and that variable is then used in comparison (for instance see [_ops/ops_eigen_diag.cc:244-252_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ops/ops_eigen_diag.cc#L244-L252)).

### value

These cases compare value obtained from tested calculation against value obtained from reference calculation.
Most probably should use tolerance-based comparisons instead of exact ones (even if integer values are actually used at this particular moment - like for the time steps).

* _ode_steppers_:
  - [_ode_steppers/ode_rk4_custom_ind_var_type_eigen.cc:14-16_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ode_steppers/ode_rk4_custom_ind_var_type_eigen.cc#L14-L16)
  - [_ode_steppers/ode_rk4_simple_correctness_eigen.cc:12-14_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ode_steppers/ode_rk4_simple_correctness_eigen.cc#L12-L14)
  - [_ode_steppers/ode_bdf1_simple_correctness_eigen.cc:61-63_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ode_steppers/ode_bdf1_simple_correctness_eigen.cc#L61-L63)
  - [_ode_steppers/ode_bdf2_simple_correctness_eigen.cc_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ode_steppers/ode_bdf2_simple_correctness_eigen.cc): lines 31-33 and 62-64
  - [_ode_steppers/ode_all_explicit_schemes_fixed_mass_matrix_correctness_eigen.cc:89_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ode_steppers/ode_all_explicit_schemes_fixed_mass_matrix_correctness_eigen.cc#L89)
  - [_ode_steppers/ode_all_explicit_schemes_varying_mass_matrix_correctness_eigen.cc_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ode_steppers/ode_all_explicit_schemes_varying_mass_matrix_correctness_eigen.cc#L113): lines 91 and 113
* _rom_:
  - [_rom/lspg_unsteady/main1.cc_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/rom/lspg_unsteady/main1.cc): lines 116, 122, 149, 155, 185, 191, 218, 224
  - [_rom/lspg_unsteady/main4.cc_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/rom/lspg_unsteady/main4.cc): lines 70, 76, 103, 109, 139, 145, 172, 178
  - [_rom/lspg_steady/main1.cc_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/rom/lspg_steady/main1.cc): lines 89, 113
  - [_rom/lspg_steady/main3.cc_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/rom/lspg_steady/main1.cc): lines 96, 120
  - [_rom/lspg_steady/main4.cc_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/rom/lspg_steady/main1.cc): lines 98, 122
### literal `sqrt()`

These cases compare against `std::sqrt(NUM_LITERAL)` - assuming certain accuracy of the standard function (correctly or not):

* _ops_
  - [_ops/ops_epetra_vector.cc:93_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ops/ops_epetra_vector.cc#L93)
  - [_ops/ops_tpetra_vector.cc:99_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ops/ops_tpetra_vector.cc#L99)
  - [_ops/ops_tpetra_block_vector.cc:99_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/ops/ops_tpetra_block_vector.cc#L99)
* _solvers_nonlinear_:
  - [_solvers_nonlinear/operators.cc_](https://github.com/Pressio/pressio/blob/7d2dbb9c324775e123173f5869da75c046bcb83d/tests/functional_small/solvers_nonlinear/operators.cc): lines: 31, 60, 249, 268, 297, 319, 352, 429

**Comment by fnrizzi** [comment]
i agree with this , if you want to make a PR for the changes that would be great
