### ISSUE TITLE
containers: add functionality to multivector for [ ] method

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#50]
Add functionality such that an object of type pressio::containers::MultiVector<....>
has the method "operator[](int i)", which returns the ith column of the multivector.

**Comment by mhoemmen** [comment]
I'm not a huge fan of overloading `operator[]` in this way for MultiVector.

1. A MultiVector is not a container of Vectors.  For instance, `std::vector<Vector>::operator[]` returns `Vector&`, with the implication that users could assign an arbitrary Vector (say, with a different Map) to it.  You're not allowed to assign an arbitrary Vector to a column of a MultiVector.

2. It's not consistent with the behavior of `Kokkos::View`, or of `mdspan` (currently in LWG wording review with a target of C++23).  A more consistent approach would be to have a nonmember function that takes a MultiVector (by const reference) and a column index, and returns a Vector that views the input MultiVector.

3. A lot of MultiVectors in practice have a single column, and users treat them as Vectors (one could perhaps blame Belos for this practice).  Users would expect a Vector's `operator[]` to return `double&`, not `Vector` or (worse yet) `RCP<Vector>`.

**Comment by fnrizzi** [comment]
@mhoemmen 
* does Kokkos:MultiVector still support []? 
* ok, so if we need a collection of vectors, you would suggest then to use a vector of vectors?

**Comment by fnrizzi** [comment]
For the sake of clarity, I should also add that `pressio::containers::MultiVector` is a wrapper for something such that within pressio we can treat it as a multivector (in the sense that you mentioned in your point 1) and that might have consequences on how we do some operations.

For example, let's take Kokkos. Users can (currently) do this:  
```c++
using kv_t = Kokkos:View<double**>;
using pressio_mv_t = pressio::containers::MultiVector<kv_t>;
pressio_mv_t A(...);

using pressio_mat_t = pressio::containers::Matrix<kv_t>;
pressio_mat_t B(...);
```
What does this mean? 
For example, let's say I have to compute inside pressio `A^T A` and `B^T B`, then I can do: 
```c++
some_return_type_here = pressio::containers::ops::dot_self(A);
some_return_type_here = pressio::containers::ops::dot_self(B);
```
where the two`dot_self` *might* (if needed) be differentiated. Both of them underneath (for now) use `KokkosBlas::gemm(...)`. But *if* we later want to handle the implementation for multivectors differently from what we do with matrices, then we can do that. For example, we might want to use some other operation to perform the computation.  

Just to clarify, in pressio a multivector is *not* a vector of vector.
I thought of adding this comment just to give some perspective.

**Comment by mhoemmen** [comment]
Thanks for explaining! :) My main concern was just to avoid confusion.  `operator[]` means "array indexing" in C++, so much so that people complain about `Kokkos::View` using `operator()` instead.  In fact, there are C++ language proposals to fix operator comma (yes, `operator,` can be overloaded; please don't :) ) so that classes could use `operator[]` instead of `operator()` for multidimensional array indexing.

**Comment by fnrizzi** [comment]
> In fact, there are C++ language proposals to fix operator comma (yes, `operator,` can be overloaded; please don't :) ) 

that sounds horrible in my view :)

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> that is scary, in my view :)

Boost.Spirit is the main culprit.  There were a few WG21 papers this year that would slowly chip away at the worst parts of overloading `operator,`.  _Non_overloaded `operator,` is useful in a few cases, esp. in fold expressions.

> So what I wrote above makes sense to you? Any other concerns?

It does -- thanks for the explanation!  Regarding MultiVectors: they exist mainly because of Anasazi, for block iterative eigensolvers.  Belos exists because of Anasazi.  MultiVectors were never intended to support the "distributed dense matrix" case, though people do use them that way.  Some of their features only make sense in the context of block iterative solvers.  The "view of noncontiguous columns" feature is the best example -- it complicates MultiVector a lot, for pretty much no performance benefit.

**Comment by fnrizzi** [comment]
@eparish1 
I added the following functionality: 
```c++
// assume b is a pressio::containers::MultiVector<Eigen::MatrixXd>, and size is `(rb,cb)`
const auto colVec = b.viewColumnVector(j);
```
`colVec` is an expression, so nothing is evaluated until you use it. `colVec` has `rb` entries and `colVec` behaves like a vector. You can do two things (for now): 
* index the colVec as you would for a vector, e.g. `colVec[i]` 
* or you can use it to compute the product `A * colVec` where `A` is a multivector by doing this:  
`auto c1 = pressio::containers::ops::product(A, colVec);`
Of course, you need to make sure the num of cols of `A` = `rb`. 
```
This works for Kokkos too.

**Comment by mhoemmen** [comment]
> This works for Kokkos too.

Just curious -- does that mean that the vector expression's `operator()` decides whether to return a reference to host or device memory, based on whether it's running on host or device?

**Comment by fnrizzi** [comment]
> > This works for Kokkos too.
> 
> Just curious -- does that mean that the vector expression's `operator()` decides whether to return a reference to host or device memory, based on whether it's running on host or device?

Good point! I omitted some details :) 
Right now, what i mean by saying it works for Kokkos is that only
```c++
auto c1 = pressio::containers::ops::product(A, colVec);
```
works for Kokkos, because I disabled the `operator[]` for an expression involving Kokkos. 
So, regading `ops::product`, I specialize for when I am dealing with operations between Kokkos types. So what happens is that when I need to compute product of `A` with an expression that involves Kokkos, the `operator()` of the expression returns a Kokkos subview, and so I still use the `KokkosBlas::gemv` on that 1d subview.

**Comment by eparish1** [comment]
@fnrizzi This is great! Yes, this covers everything i believe!

**Comment by fnrizzi** [comment]
closing the issue for now since for now it is addressed

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> Does this make sense?

Yes -- thanks for explaining! :-D

**Comment by fnrizzi** [comment]
cc77137bb42371a9cd18ce80c2521b096a736dba
