### ISSUE TITLE
clang compiler warnings for comparing incompatible types in ops/eigen/ops_elementwise_multiply.hpp

### ISSUE THREAD

**Issue by pjb236** [Pressio/pressio#505]
The assertions on lines 82 and 83 currently compare a long to an unsigned long, provoking a warning from the clang compiler. 

The warning was suppressed by modifying the assertions as follows:

  assert(::pressio::ops::extent(x, 0)==long(::pressio::ops::extent(z, 0)));
  assert(long(::pressio::ops::extent(z, 0))==::pressio::ops::extent(y, 0));

If this is acceptable, we should make this change on github as well.

**Comment by fnrizzi** [comment]
this is weird, are you sure it happens in ops/eigen/ops_elementwise_multiply.hpp? 
In any case, we should do: 
```
assert( std::size_t(::pressio::ops::extent(x, 0)) == std::size_t(::pressio::ops::extent(z, 0)) );
assert( std::size_t(::pressio::ops::extent(z, 0)) == std::size_t(::pressio::ops::extent(y, 0)) );
```

**Comment by fnrizzi** [comment]
if you want to open a PR for this it would be great, or I can too

**Comment by pjb236** [comment]
> this is weird, are you sure it happens in ops/eigen/ops_elementwise_multiply.hpp? In any case, I would say we should do:
> 
> ```
> assert( std::size_t(::pressio::ops::extent(x, 0)) == std::size_t(::pressio::ops::extent(z, 0)) );
> assert( std::size_t(::pressio::ops::extent(z, 0)) == std::size_t(::pressio::ops::extent(y, 0)) );
> ```

Yes, I am certain it happens in ops/eigen/ops_elementwise_multiply.hpp, when I recast the types as stated in the original issue comment the error went away. 

PR=pull request?

**Comment by fnrizzi** [comment]
ok, thanks for that! i have to check why it happens though... i don't understand why extent on x and y and z returns different types!

**Comment by mzuzek** [comment]
Hi!

For native Eigen containers [`::pressio::ops::extent()`](https://github.com/Pressio/pressio/blob/develop/include/pressio/ops/eigen/ops_extent.hpp#L54-L80) returns `decltype(std::declval<const T>().size())` which resolves to `EIGEN_DEFAULT_DENSE_INDEX_TYPE` (through [`Eigen::Index`](https://eigen.tuxfamily.org/dox/namespaceEigen.html#a62e77e0933482dafde8fe197d9a2cfde) returned by [`EigenBase::size()`](https://eigen.tuxfamily.org/dox/structEigen_1_1EigenBase.html)), which is configurable but defaults to **`std::ptrdiff_t`**.

For Eigen expressions [`::pressio::ops::extent()`](https://github.com/Pressio/pressio/blob/develop/include/pressio/ops/eigen/ops_extent.hpp#L82-L90) returns `decltype(std::declval<const T>().extent(0))` which resolves to **`size_t`** for all expression types (see [`AsDiagonalMatrixExpr`](https://github.com/Pressio/pressio/blob/develop/include/pressio/expressions/impl/asdiagonalmatrix_classes.hpp#L92), [`DiagExpr`](https://github.com/Pressio/pressio/blob/develop/include/pressio/expressions/impl/diag_classes.hpp#L96), [`SpanExpr`](https://github.com/Pressio/pressio/blob/develop/include/pressio/expressions/impl/span_classes.hpp#L98) and [`SubspanExpr`](https://github.com/Pressio/pressio/blob/develop/include/pressio/expressions/impl/subspan_classes.hpp#L115)).

I guess it's **`long`** (`std::ptrdiff_t`) for `x` and `y` here because they're native containers and it's **`unsigned long`** (`size_t`) for `z` because it's an expression ?

**Comment by fnrizzi** [comment]
@mzuzek good catch!! we need to fix this

**Comment by mzuzek** [comment]
> @mzuzek good catch!! we need to fix this , we need to fix the expressions so that the return type is consistent. do you agree or disagree?

@fnrizzi Yes, adjusting the extent types in expressions for consistency seems like the best idea!

**Comment by fnrizzi** [comment]
i think this was done
