### ISSUE TITLE
Add mutivector_dot_multivector for, e.g., eigen, kokkos

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#54]
Various data types (e.g., eigen and Kokkos) currently don't have operations for dotting two multivectors together, i.e., 

containers_mvec_dot_mvec.hpp

Note that these data types _do_ have operations for dotting a multivector with itself,

containers_mvec_dot_self.hpp

For WLS, if the local Jacobian type Jphi is a multivector, we require the containers_mvec_dot_mvec.hpp.

**Comment by mhoemmen** [comment]
What does "dotting two multivectors together" mean?  Does that mean columnwise, as a vector of results `results(j) = dot(X(:, j), Y(:, j))`, or does it mean "matrix-matrix product X^T * Y"?

**Comment by fnrizzi** [comment]
> What does "dotting two multivectors together" mean? Does that mean columnwise, as a vector of results `results(j) = dot(X(:, j), Y(:, j))`, or does it mean "matrix-matrix product X^T * Y"?

Here it is actually intended as X^T * Y. I know that for tpetra dot refers to dotting pairs of vectors. But 
 in pressio we could call this one something like `pairWiseDot`. I am open to suggestions :) I would be happy to change the definitions to make it more clear.

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> Here it is actually intended as X^T * Y. I know that for tpetra dot refers to dotting pairs of vectors.

`KokkosBlas::gemm` implements the per-MPI-process part of this case in Tpetra; `Tpetra::MultiVector::multiply` implements the (MPI-)global case.

**Comment by fnrizzi** [comment]
> @fnrizzi wrote:
> 
> > Here it is actually intended as X^T * Y. I know that for tpetra dot refers to dotting pairs of vectors.
> 
> `KokkosBlas::gemm` implements the per-MPI-process part of this case in Tpetra; `Tpetra::MultiVector::multiply` implements the (MPI-)global case.

yes, agreed!  
It seemed to me you did not like very much the naming convention. You have suggestions? We could have a `multiply` with optional transposition and get rid of the dot. Or leave the dot and then add another one like `pairWiseDot`.

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> It seemed to me you did not like very much the naming convention. You have suggestions? We could have a `multiply` with optional transposition and get rid of the dot. Or leave the dot and then add another one like `pairWiseDot`. I am open to suggestions ;)

Thanks for being open! :-D  It's really up to y'all how to name things.  Trilinos has chosen to provide a common interface for vectors and multivectors, so "dot" has to mean analogous things for both vectors and multivectors in Trilinos.  That's why Trilinos uses a different name ("multiply") for `X^T * Y`.

I'm not attached to how Trilinos does things.  For example, `{E,T}petra::Vector` being a subclass of `{E,T}petra::MultiVector` is suboptimal design; it's an example of the classic "circles are not special ellipses" inheritance antipattern.  Also, Anasazi and Belos confuse "block of vectors" with "memory pool from which to allocate blocks of vectors," and use MultiVector to represent both.  This is why MultiVectors must be column major, even though row-major multivectors would make block iterative solvers faster with simpler code.  Thus, if you want to do things better in Pressio, please feel free :-) .

**Comment by fnrizzi** [comment]
> MultiVectors must be column major

agreed!


>Thus, if you want to do things better in Pressio, please feel free :-) .

ah! will try :)

**Comment by fnrizzi** [comment]
@eparish1  
let's say you have to do: A^T A, where A is a MV. Currently, in pressio you can do: 
```c++
... = pressio::containers::ops::dot_self(A);
```
do you need also support for doing A^T B, where both A,B are MV but not necessarily the same?

**Comment by eparish1** [comment]
@fnrizzi 

Yes, this is correct. We need support for doing A^T B, where both A and B are MV but not the same. This is currently supported for tpetra, but not the others.  

Specifically what I need for WLS is the ability to do an operation like:

for j in range(0,numStepsInWindow):
  start_index = ...
  end_index = ...  
  J1 = ...
  J2 = ...
  **Hessian[start_index:end_index,start_index:end_index] = J1^T J2**

The issue of viewing into the Hessian is related to issue #53 

At the fundamental level, we need the ability to to C = A^T B, when A and B are multi vectors.

**Comment by mhoemmen** [comment]
@eparish1 You should be able to call `KokkosBlas::gemv` for the intraprocess part of this operation, as long as you can express the local data as some kind of rank-2 `Kokkos::View`.
