### ISSUE TITLE
ode: Allow for time step failure.

### ISSUE THREAD

**Issue by vbrunini** [Pressio/pressio#90]
I'd like a mechanism to be able to trigger a time step to fail & retry with a shorter time step (say half the previous attempt) as a mechanism for improving robustness. I'd like to be able to trigger this from either timeDiscreteResidual or applyTimeDiscreteJacobian calls in my model. Probably also need a mechanism to supply a minimum time step size the run should fail entirely at if the time step is continually being cut back.

**Comment by fnrizzi** [comment]
@vbrunini, I am working on it. Will ping you soon with some thoughts

**Comment by fnrizzi** [comment]
@vbrunini 
After some thinking, I have reached (at least) one key thing to address first: _how the user should trigger the event?_
For now, let's assume we trigger the event inside the `discreteTimeResidual` function, which in my view makes sense since it is always called first and you also said you prefer it over the jacobian. 
In my view, we have two options: 
- (A) you trigger it by reporting to pressio something as below (using the expected idiom): 
```c++
pressio::utils::eh::Expected<void> discreteTimeResidual(...) const
{
  // do what you need to do 
  // ...
  if (something) return pressio::utils::eh:failed_residual_evaluation();
  // ...
  return {};
} 
```
- (B) or you can trigger using an exception: 
```c++
void discreteTimeResidual(...) const{
 //...
 if (something) throw pressio::utils::eh:failed_residual_evaluation();
 //...
}
```

I would say that the advantage of (A) is that you only store the exception, and Pressio would handle the return object and do something with it, not necessarily right away but maybe later. Also, pressio can handle it, if needed, without explicitly calling the try/catch, which is the point of the expected idiom which has some advantages. 
The advantage of (B) is that it is a standard exception.  
Q: do you envision having multiple reasons for failing? if so, this might change things and that is why I emailed you. 
For instance, we could have the case where the residual is evaluated but we can still attempt a solution, or the case where it makes no sense at all to attempt one.

**Comment by fnrizzi** [comment]
@vbrunini i have this almost ready, just adding a couple tests and will send it your way
